variable "backend" {
  description = "(optional) - Unique name of the auth backend to configure."
  type        = string
  default     = null
}

variable "bind_secret_id" {
  description = "(optional) - Whether or not to require secret_id to be present when logging in using this AppRole."
  type        = bool
  default     = null
}

variable "bound_cidr_list" {
  description = "(optional) - List of CIDR blocks that can log in using the AppRole."
  type        = set(string)
  default     = null
}

variable "period" {
  description = "(optional) - Number of seconds to set the TTL to for issued tokens upon renewal. Makes the token a periodic token, which will never expire as long as it is renewed before the TTL each period."
  type        = number
  default     = null
}

variable "policies" {
  description = "(optional) - Policies to be set on tokens issued using this AppRole."
  type        = set(string)
  default     = null
}

variable "role_id" {
  description = "(optional) - The RoleID of the role. Autogenerated if not set."
  type        = string
  default     = null
}

variable "role_name" {
  description = "(required) - Name of the role."
  type        = string
}

variable "secret_id_bound_cidrs" {
  description = "(optional) - List of CIDR blocks that can log in using the AppRole."
  type        = set(string)
  default     = null
}

variable "secret_id_num_uses" {
  description = "(optional) - Number of times which a particular SecretID can be used to fetch a token from this AppRole, after which the SecretID will expire. Leaving this unset or setting it to 0 will allow unlimited uses."
  type        = number
  default     = null
}

variable "secret_id_ttl" {
  description = "(optional) - Number of seconds a SecretID remains valid for."
  type        = number
  default     = null
}

variable "token_bound_cidrs" {
  description = "(optional) - Specifies the blocks of IP addresses which are allowed to use the generated token"
  type        = set(string)
  default     = null
}

variable "token_explicit_max_ttl" {
  description = "(optional) - Generated Token's Explicit Maximum TTL in seconds"
  type        = number
  default     = null
}

variable "token_max_ttl" {
  description = "(optional) - The maximum lifetime of the generated token"
  type        = number
  default     = null
}

variable "token_no_default_policy" {
  description = "(optional) - If true, the 'default' policy will not automatically be added to generated tokens"
  type        = bool
  default     = null
}

variable "token_num_uses" {
  description = "(optional) - The maximum number of times a token may be used, a value of zero means unlimited"
  type        = number
  default     = null
}

variable "token_period" {
  description = "(optional) - Generated Token's Period"
  type        = number
  default     = null
}

variable "token_policies" {
  description = "(optional) - Generated Token's Policies"
  type        = set(string)
  default     = null
}

variable "token_ttl" {
  description = "(optional) - The initial ttl of the token to generate in seconds"
  type        = number
  default     = null
}

variable "token_type" {
  description = "(optional) - The type of token to generate, service or batch"
  type        = string
  default     = null
}

